# tell netlify about your build script and output directory

[build]
  command = "npm run build"
  publish = "dist"
  node_version = "20"

# Redirect any URLs with the language code in them already
[[redirects]]
  from = "/sv/*"
  to = "/:splat"
  status = 301
  force = true

# Important: Per shadowing rules, URLs for the
# _non-default_ language-specific content files
# are served without redirects.

# Redirect for end-user’s browser preference override
[[redirects]]
  from = "/*"
  to = "/en/:splat"
  status = 302
  conditions = {Language = ["en"]}

# Default
[[redirects]]
  from = "/*"
  to = "/sv/:splat"
  status = 200

